name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
        
    - name: Build
      run: |
        npm run build
        
    - name: Zip
      run: |
        zip -r ./chrome-extension.zip ./dist
    
    - name: GetVersion
      id: get_chrome_extension_version
      run: |
          VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "v0.0.1")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version:${VERSION}"
          
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
          token: ${{ secrets.MY_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./chrome-extension.zip
